import { Services } from "@/types";

export const SERVICES: Services[] = [
    {
        id: 1,
        imgSrc: "/images/service-icons/service-icon-1.webp",
        name: "Dental Checkup",
        text: "Routine examination and cleaning to maintain healthy teeth and gums.",
        href: "/#dental-checkup",
        idStr: "dental-checkup",
    },
    {
        id: 2,
        imgSrc: "/images/service-icons/service-icon-2.webp",
        name: "X-RAY",
        text: "Advanced imaging to detect hidden dental problems and plan precise treatments.",
        href: "/#x-ray",
        idStr: "x-ray",
    },
    {
        id: 3,
        imgSrc: "/images/service-icons/service-icon-3.webp",
        name: "Teeth Whitening",
        text: "Professional brightening treatment to remove stains and enhance your smile.",
        href: "/#teeth-whitening",
        idStr: "teeth-whitening",
    },
    {
        id: 4,
        imgSrc: "/images/service-icons/service-icon-4.webp",
        name: "Gingivitis Periodontitis",
        text: "Specialized treatment for gum disease to restore healthy gums and prevent tooth loss.",
        href: "/#gingivitis-periodontitis",
        idStr: "gingivitis-periodontitis",
    },
    {
        id: 5,
        imgSrc: "/images/service-icons/service-icon-5.webp",
        name: "Composite and GIC Restoration",
        text: "Tooth-colored fillings to repair cavities and restore natural appearance.",
        href: "/#composite-and-gic-restoration",
        idStr: "composite-and-gic-restoration",
    },
    {
        id: 6,
        imgSrc: "/images/service-icons/service-icon-6.webp",
        name: "RCT",
        text: "Root canal treatment to save infected teeth and eliminate pain.",
        href: "/#rct",
        idStr: "rct",
    },
    {
        id: 7,
        imgSrc: "/images/service-icons/service-icon-7.webp",
        name: "Oral Surgery",
        text: "Surgical procedures for tooth extraction and complex dental treatments.",
        href: "/#oral-surgery",
        idStr: "oral-surgery",
    },
    {
        id: 8,
        imgSrc: "/images/service-icons/service-icon-8.webp",
        name: "CD, RPD, FPD",
        text: "Custom dentures and bridges to replace missing teeth and restore function.",
        href: "/#cd-rpd-fpd",
        idStr: "cd-rpd-fpd",
    },
    {
        id: 9,
        imgSrc: "/images/service-icons/service-icon-9.webp",
        name: "Extraction",
        text: "Safe tooth removal procedures for damaged or problematic teeth.",
        href: "/#extraction",
        idStr: "extraction",
    },
    {
        id: 10,
        imgSrc: "/images/service-icons/service-icon-10.webp",
        name: "Orthodontic Treatment",
        text: "Braces and aligners to straighten teeth and correct bite alignment.",
        href: "/#orthodontic-treatment",
        idStr: "orthodontic-treatment",
    },
    {
        id: 11,
        imgSrc: "/images/service-icons/service-icon-11.webp",
        name: "Dental Crown",
        text: "Custom caps to protect and restore damaged or weakened teeth.",
        href: "/#dental-crown",
        idStr: "dental-crown",
    },
    {
        id: 12,
        imgSrc: "/images/service-icons/service-icon-12.webp",
        name: "Halitosis Treatment",
        text: "Specialized care to eliminate bad breath and restore fresh confidence.",
        href: "/#halitosis-treatment",
        idStr: "halitosis-treatment",
    },
    {
        id: 13,
        imgSrc: "/images/service-icons/service-icon-13.webp",
        name: "Boil Treatment",
        text: "Professional care to treat oral boils and prevent painful infections.",
        href: "/#boil-treatment",
        idStr: "boil-treatment",
    },
    {
        id: 14,
        imgSrc: "/images/service-icons/service-icon-14.webp",
        name: "Scaling",
        text: "Professional plaque and tartar removal to maintain healthy gums and teeth.",
        href: "/#scaling",
        idStr: "scaling",
    },
    {
        id: 15,
        imgSrc: "/images/service-icons/service-icon-15.webp",
        name: "Polishing",
        text: "Professional tooth polishing to remove stains and restore natural shine.",
        href: "/#polishing",
        idStr: "polishing",
    },
    {
        id: 16,
        imgSrc: "/images/service-icons/service-icon-16.webp",
        name: "Trauma Management",
        text: "Emergency care for dental injuries to save and restore damaged teeth.",
        href: "/#trauma-management",
        idStr: "trauma-management",
    },
    {
        id: 17,
        imgSrc: "/images/service-icons/service-icon-17.webp",
        name: "Full Mouth Rehabilitation",
        text: "Comprehensive restoration to rebuild and transform your entire smile.",
        href: "/#full-mouth-rehabilitation",
        idStr: "full-mouth-rehabilitation",
    },
    {
        id: 18,
        imgSrc: "/images/service-icons/service-icon-18.webp",
        name: "Teeth Implant",
        text: "Permanent solution to replace missing teeth with natural strength.",
        href: "/#teeth-implant",
        idStr: "teeth-implant",
    },
    {
        id: 19,
        imgSrc: "/images/service-icons/service-icon-19.webp",
        name: "Flouride Application",
        text: "Professional treatment to strengthen tooth enamel and prevent cavities effectively.",
        href: "/#flouride-application",
        idStr: "flouride-application",
    },
    {
        id: 20,
        imgSrc: "/images/service-icons/service-icon-6.webp",
        name: "Pulpectomy/Pulpotomy",
        text: "Root canal treatment to save infected teeth and restore healthy function",
        href: "/#pulpectomy",
        idStr: "pulpectomy",
    },
    {
        id: 21,
        imgSrc: "/images/service-icons/service-icon-20.webp",
        name: "Growth Modification",
        text: "Orthodontic treatment to guide jaw development and improve facial harmony",
        href: "/#growth-modification",
        idStr: "growth-modification",
    },
    {
        id: 22,
        imgSrc: "/images/service-icons/service-icon-21.webp",
        name: "Myofunctional Appliance Therapy",
        text: "Corrective devices to retrain oral muscles and improve breathing patterns.",
        href: "/#myofunctional-appliance-therapy",
        idStr: "myofunctional-appliance-therapy",
    },
    {
        id: 23,
        imgSrc: "/images/service-icons/service-icon-9.webp",
        name: "Surgical Extraction",
        text: "Advanced removal of complex or impacted teeth with specialized techniques.",
        href: "/#surgical-extraction",
        idStr: "surgical-extraction",
    },
];